blog_news_portal_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.conf import settings
from news.views import HomePageView, ArticleDetailView, RegisterView, news_likes, CommentsView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', HomePageView.as_view(), name='homepage'),
                  path('article/<int:pk>', ArticleDetailView.as_view(), name='article'),
                  path('article/<int:pk>/like', news_likes, name='news_likes'),
                  path('article/<int:pk>/comment', CommentsView.as_view(), name='article_comment'),
                  path('register/', RegisterView.as_view(), name='register'),
                  path('login/', LoginView.as_view(template_name='login.html'), name='login'),
                  path('logout/', LogoutView.as_view(), name='logout'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=40)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class News(models.Model):
    title = models.CharField(max_length=60)
    description = models.TextField(default=None, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)
    source = models.CharField(max_length=30, blank=True, null=True)
    likes = models.ManyToManyField(get_user_model(), related_name='news_likes')

    class Meta:
        verbose_name = 'news'
        verbose_name_plural = 'news'

    def __str__(self):
        return f"{self.title}"

    def number_of_likes(self):
        return self.likes.count


class CommentsModel(models.Model):
    article = models.ForeignKey(News, on_delete=models.PROTECT)
    posted_by = models.ForeignKey(User, on_delete=models.PROTECT)
    comment = models.TextField()
    post_date = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        ordering = ['-post_date']

    def __str__(self):
        return f'{self.article.__str__()} {self.comment} by : {self.posted_by.get_full_name()}'


class Banner(models.Model):
    name = models.CharField(max_length=60)
    image = models.ImageField()
    url = models.URLField(blank=True)
    posted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'banner'
        verbose_name_plural = 'banners'

    def __str__(self):
        return self.name

news/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from news.models import CommentsModel


class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user


class CommentsForm(forms.ModelForm):

    class Meta:
        model = CommentsModel
        fields = ('comment',)
        widgets = {
            'comment': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter your comment here',
                    'rows': 4,  # Set the number of visible text lines
                    'cols': 50,  # Set the visible width of the text area
                    'style': 'resize: vertical;',  # Allow vertical resizing of the text area
                    'autofocus': True,  # Automatically focus on the comment field when the page loads
                    'autocomplete': 'on',  # Enable browser autocomplete for the comment field
                    'spellcheck': True,  # Enable spell checking for the comment field
                }
            ),
        }

news/views.py
# from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, FormView

from news.forms import NewUserForm, CommentsForm
from news.models import News


# Create your views here.
class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['News'] = News.objects.all().order_by('-created_at')
        return context


class ArticleDetailView(TemplateView):
    template_name = 'article_details.html'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context['article'] = News.objects.get(pk=kwargs.get('pk'))
        context['comment_form'] = CommentsForm
        return context


class RegisterView(FormView):
    template_name = 'register.html'
    form_class = NewUserForm
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def news_likes(request, pk):
    news = get_object_or_404(News, pk=pk)
    if news.likes.filter(id=request.user.id).exists():
        news.likes.remove(request.user)
    else:
        news.likes.add(request.user)
    return HttpResponseRedirect(reverse('article', args=[str(pk)]))


class CommentsView(FormView):
    form_class = CommentsForm
    # success_url = 'article'

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.posted_by = self.request.user
        comment.article = News.objects.get(pk=self.kwargs.get('pk'))
        comment.save()
        return HttpResponseRedirect(reverse('article', args=[self.kwargs.get('pk')]))

templates/article_details.html
{% extends 'layout.html' %}
{% block content %}
    <div class="col-12 bg-light my-5">
        <div class="col-12 d-flex">
            <div class="col-5 p-3">
                <p>{{ article.category.name }}</p>
                <h2>{{ article.title }}</h2>
                <p>{{ article.created_by.get_full_name }}</p>
                <p class="text-secondary">{{ article.created_at }}</p>
            </div>
            <div class="col-7 p-3">
                {% if article.image_url %}
                    <img width="100%" src="{{ article.image_url }}" alt="article pic">
                {% else %}
                <img width="100%" src="{{ article.image.url }}" alt="article pic">
                {% endif %}
                <span style="position: relative; display: inline-block;">
    <a class="btn-danger" href="{% url 'news_likes' article.pk %}" style="text-decoration: none; color: inherit;">
        <i class="fa fa-heart"></i>
    </a>
    <span style="position: absolute; top: -10px; right: -10px; background-color: #ff5c62; color: #fff; width: 20px; height: 20px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 12px;">
        {{ article.likes.count }}
    </span>
</span>
            </div>
        </div>
        <div class="col-12 p-3">
            <p class='text-secoarticledary'>{{ article.description|safe }}</p>
        </div>
        <div class="col-12 p-3">
            <h3>Comments</h3>
            {% for comment in article.commentsmodel_set.all %}
                <div class="comment">
                    <p>commenter: <i>{{ comment.posted_by.get_full_name }}</i>
                        <br>{{ comment.comment }}
                        <br> comment date: {{ comment.post_date }}</p>
                </div>
            {% endfor %}
        </div>
        <div class="col-12 p-3">
            <h3>Add a Comment</h3>
            <form method="post" action="{% url 'article_comment' article.id %}">
                {% csrf_token %}
                {{ comment_form }}
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block content %}
    {% for i in News %}
        <div class="col-12 d-flex bg-light my-5">
            <div class="col-4 p-3">
                <p>{{ i.category.name }}</p>
                <h2><a class=" btn btn-info" href="{% url 'article' i.pk %}">{{ i.title }}</a></h2>
                <p>{{ i.created_by.get_full_name }}</p>
                <p class="text-secondary">{{ i.created_at }}</p>
                <span style="position: relative; display: inline-block;">
    <a class="btn-danger" href="{% url 'news_likes' i.pk %}" style="text-decoration: none; color: inherit;">
        <i class="fa fa-heart"></i>
    </a>
    <p style="position: absolute; top: -10px; right: -10px; background-color: #ff5c62; color: #fff; width: 20px; height: 20px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 12px;">
        {{ i.likes.count }}
    </p>
</span>

            </div>
            <div class="col-4 p-3">
                <p class='text-secondary'>{{ i.description|safe }}</p>
            </div>
            <div class="col-4 p-3">
                {% if i.image_url %}

                    <img width="100%" src="{{ i.image_url }}">
                {% else %}
                    <img width="100%" src="{{ i.image.url }}">
                {% endif %}
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News Portal</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
</head>
<body class="bg-primary p-5">
<div class="navbar  navbar-fixed-top navbar-light bg-light p-2">
    <a class="btn btn-info" href="{% url 'homepage' %}"> news portal</a>
    {% if request.user.is_authenticated %}
        <span>{{ request.user.username }}&nbsp; <form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-info">Logout</button>
</form></span>
    {% else %}
        <div>
            <a class="btn btn-success me-2" href="{% url 'login' %}" role="button">Login</a>
            <a class="btn btn-success" href="{% url 'register' %}" role="button">Register</a>
        </div>
    {% endif %}
</div>
<div class="container d-flex">
    <div class="col-9 ">
        {% block content %}

        {% endblock %}
    </div>
    <div class="col-3 p-5">
        {% for banner in banners %}
            <div class="bg-light mb-5">
                <a href="{{ banner.url }}" class="btn btn-outline-success" target="_blank">
                    <img width="100%" src="{{ banner.image.url }}">
                </a>
            </div>
        {% endfor %}
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
{% block extra_scripts %}

{% endblock %}
</body>
<footer>
    news portal by erfan naderi for sama janatabad university
</footer>
</html>

templates/login.html
{% extends 'layout.html' %}
{% block content %}
        <div class="container bg-light py-5 my-3 visible-md-block">
        <h1 class="">Login </h1>
        <form method="post">
            {% csrf_token %}
            {{ form}}
            <button type="submit" class="btn btn-info">Sign In</button>
        </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container bg-light py-5 my-3 visible-md-block">
        <h1>Register</h1>
        <form method="post">
            {% csrf_token %}
            {{ form}}
            <button type="submit" class="btn btn-info">Sign Up</button>
        </form>
    </div>
{% endblock %}